%dev,test.quarkus.hibernate-orm.sql-load-script=chuck_norris_db.sql
%dev.quarkus.http.cors=true
%dev.quarkus.http.cors.origins=http://localhost:4200
%dev.quarkus.http.cors.methods=GET,POST,PUT,DELETE
%dev.quarkus.http.cors.headers=Content-Type,Authorization
%dev.quarkus.http.cors.exposed-headers=X-Total-Count
%dev.quarkus.http.cors.access-control-allow-credentials=true

# Configuration de l'authentification
%dev,test.quarkus.keycloak.devservices.port=8180
%test.test-url-keycloak=http://localhost:8180/realms/app/protocol/openid-connect/token
%dev,test.quarkus.keycloak.devservices.realm-path=app-realm.json
%dev,test.mp.jwt.verify.publickey.location=http://localhost:8180/realms/app/protocol/openid-connect/certs
%dev,test.quarkus.oidc.client-id=back
%dev,test.quarkus.oidc.credentials.secret=secret
%dev.quarkus.oidc.token.issuer=http://localhost:8180/realms/app



# Configuration des chemins publics et prot�g�s
quarkus.http.auth.permission.public.paths=/*
quarkus.http.auth.permission.public.policy=permit
quarkus.http.auth.permission.public.methods=GET

# Configuration des chemins authentifi�s
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.http.auth.permission.authenticated.methods=POST,PUT,DELETE

# logging
%dev.quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".level=TRACE
%dev.quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".min-level=TRACE
%dev.quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG
