INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris is the only human being to display the Heisenberg uncertainty principle - you can never know both exactly where and how quickly he will roundhouse-kick you in the face.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris invented the bolt-action rifle, liquor, sexual intercourse, and football-- in that order.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris invented a new martial arts style: Chuck-Will-Kill.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris always knows the EXACT location of Carmen SanDiego.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris'' dick is so big, it has it''s own dick, and that dick is still bigger than yours.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'He who lives by the sword, dies by the sword. He who lives by Chuck Norris, dies by the roundhouse kick.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris can be unlocked on the hardest level of Tekken. But only Chuck Norris is skilled enough to unlock himself. Then he roundhouse kicks the Playstation back to Japan.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris can exist in two or more places at the same time.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Nobody doesn''t like Sara Lee. Except Chuck Norris.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Police label anyone attacking Chuck Norris as a Code 45-11.... A suicide.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Contrary to popular belief, there is indeed enough Chuck Norris to go around.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris doesn''t have disk latency because the hard drive knows to hurry the hell up.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'The only thing you can beat Chuck Norris at is the number of times you''ve had your face kicked in.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris once spit on a lizard. The result is tyrannosaurus rex.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Never look a gift Chuck Norris in the mouth, because he will bite your damn eyes off.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'The Bermuda Triangle used to be the Bermuda Square, until Chuck Norris Roundhouse kicked one of the corners off.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'They once made Chuck Norris toilet paper. The only problem was that it wouldn''t take shit from no one!');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris just says "no" to drugs. If he said "yes", it would collapse Colombia''s infrastructure.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris knows everything there is to know - Except for the definition of mercy.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris built a better mousetrap, but the world was too frightened to beat a path to his door.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'In an average living room there are 1,242 objects Chuck Norris could use to kill you, including the room itself.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'The pen is mighter than the sword, but only if the pen is held by Chuck Norris.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris invented bacon by throwing a pig through a chain link fence.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Many rednecks and rural farmers enjoy Mountain Oysters as a special delicacy within their traditional menus. Chuck Norris, however, prefers to personally harvest and diet upon Mountain Gorilla Oysters.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'A man once asked Chuck Norris if his real name is "Charles". Chuck Norris did not respond, he simply stared at him until he exploded.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris is not Irish. His hair is soaked in the blood of his victims.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'The word ''Kill'' was invented by Chuck Norris. Other words were ''Die'', ''Beer'', and ''What''.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Crime does not pay - unless you are an undertaker following Walker, Texas Ranger, on a routine patrol.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'They once made a Chuck Norris toilet paper, but there was a problem-- It wouldn''t take shit from anybody.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, '''Hakuna Matata'' is actually Swahili for ''all hail Chuck Norris''.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris'' gaydar is so finely tuned he can tell if you have EVER stared at another man''s ass and will brutally kill you accordingly.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Most people have 23 pairs of chromosomes. Chuck Norris has 72... and they''re all poisonous.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris never wet his bed as a child. The bed wet itself out of fear.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris thinks inside the bun.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris never goes to the dentist because his teeth are unbreakable. His enemies never go to the dentist because they have no teeth.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Jack in the Box''s do not work around Chuck Norris. They know better than to attempt to scare Chuck Norris.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris will attain statehood in 2009. His state flower will be the Magnolia.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris is not dead yet because he knows Bruce Lee is waiting for him in the after life.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'If Chuck Norris had killed Kenny, he would have stayed dead.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris likes his ice like he likes his skulls: crushed.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'In the beginning there was nothing...then Chuck Norris Roundhouse kicked that nothing in the face and said "Get a job". That is the story of the universe.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'When Chuck Norris kills you, the government fully covers all funeral expenses, as ordered by the UN. It is the only truly good thing they have ever done.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'When Chuck Norris sends in his taxes, he sends blank forms and includes only a picture of himself, crouched and ready to attack. Chuck Norris has not had to pay taxes, ever.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Hellen Keller''s favorite color is Chuck Norris.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris finished World of Warcraft.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris sleeps with a pillow under his gun.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris keeps his friends close and his enemies closer. Close enough to drop them with one round house kick to the face.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'There are two types of people in the world... people that suck, and Chuck Norris.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Since 1940, the year Chuck Norris was born, roundhouse kick related deaths have increased 13,000 percent.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, '# Chuck Norris''s show is called Walker: Texas Ranger, because Chuck Norris doesn''t run.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Divide Chuck Norris by zero and you will in fact get one........one bad-ass that is.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Some people ask for a Kleenex when they sneeze, Chuck Norris asks for a body bag.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris does not play the lottery. It doesn''t have nearly enough balls.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Archeologists unearthed an old english dictionary dating back to the year 1236. It defined "victim" as "one who has encountered Chuck Norris".');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Every SQL statement that Chuck Norris codes has an implicit "COMMIT" in its end.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris invented a language that incorporates karate and roundhouse kicks. So next time Chuck Norris is kicking your ass, don?t be offended or hurt, he may be just trying to tell you he likes your hat.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris once lost the remote, but maintained control of the TV by yelling at it in between bites of his "Filet of Child" sandwich.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris owns a chain of fast-food restaurants throughout the southwest. They serve nothing but barbecue-flavored ice cream and Hot Pockets.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'A man once claimed Chuck Norris kicked his ass twice, but it was promptly dismissed as false - no one could survive it the first time.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris roundhouse kicks don''t really kill people. They wipe out their entire existence from the space-time continuum.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'No matter which part of Chuck Norris you aim at, the bullet will always hit the center of your forehead.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris could order a steak at PETA''s cafeteria and get one. But he''s far more likely to kick the shit out of all the candy-asses in the place before roundhousing the building into rubble.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris does not follow fashion trends, they follow him. But then he turns around and kicks their ass. Nobody follows Chuck Norris.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'In the X-Men movies, none of the X-Men super-powers are done with special effects. Chuck Norris is the stuntman for every character.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris uses tabasco sauce instead of visine.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'In the Bible, Jesus turned water into wine. But then Chuck Norris turned that wine into beer.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris doesn''t believe in ravioli. He stuffs a live turtle with beef and smothers it in pig''s blood.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris did in fact, build Rome in a day.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris CAN see John Cena.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'The show Survivor had the original premise of putting people on an island with Chuck Norris. There were no survivors, and nobody is brave enough to go to the island to retrieve the footage.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Those aren''t credits that roll after Walker Texas Ranger. It is actually a list of fatalities that occurred during the making of the episode.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris can watch TV...on his GameBoy...');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris chooses not to compete in an Ironman because of the swim, every time he starts kicking and swinging his arms, people die!');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'When you say "no one''s perfect", Chuck Norris takes this as a personal insult.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris doesn''t read books. He stares them down until he gets the information he wants.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'The crickets don''t chirp at Chuck Norris'' house, if they know what''s good for them.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'If you spell Chuck Norris in Scrabble, you win. Forever.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Chuck Norris''s brain waves are suspected to be harmful to cell phones.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'Who knows what evil lurks in the hearts of men? Goddamn Chuck Norris, that''s who.');
INSERT INTO Joke (id, created_at, joke) VALUES (gen_random_uuid(), CURRENT_TIMESTAMP, 'There is no such thing as global warming. Chuck Norris was cold, so he turned the sun up.');