### Récupération d'une blague
GET {{host}}:{{port}}/{{path}}/getRandomJoke
accept: application/json
Authorization: Bearer {{$auth.token("oauth2")}}

### Récupération par id
GET {{host}}:{{port}}/{{path}}/bb699cd6-4172-465d-9ebd-c7ae72917671
accept: application/json
Authorization: Bearer {{$auth.token("oauth2")}}

### Ajout d'une blague
POST {{host}}:{{port}}/{{path}}
content-type: application/json
accept: application/json
Authorization: Bearer {{$auth.token("oauth2")}}

{
  "joke": "This is a joke"
}

### Modification d'une blague
PUT {{host}}:{{port}}/{{path}}
Content-Type: application/json
accept: application/json
Authorization: Bearer {{$auth.token("oauth2")}}

{
  "id": "bb699cd6-4172-465d-9ebd-c7ae72917671",
  "created_at": "2025-04-13T21:26:02.732835",
  "joke": "This is a joke2"
}

### Suppression d'une blague
DELETE {{host}}:{{port}}/{{path}}/bb699cd6-4172-465d-9ebd-c7ae72917671
accept: application/json
Authorization: Bearer {{$auth.token("oauth2")}}
