name: Chuck Norris action

on: [push, pull_request]

env:
  JAVA_VERSION: '21'
  IMAGE_NAME: 'leeson77/chuck-norris-backend'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}  # Utiliser la variable d'environnement
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests
        run: mvn test

  native-compile:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}  # Utiliser la variable d'environnement
          distribution: 'temurin'
          cache: 'maven'

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y binfmt-support qemu-user-static

      - name: Compilation
        run: | 
          mvn clean package -Dnative -DskipTests -Dquarkus.native.container-build=true -Dquarkus.native.container-runtime-options=--platform=linux/arm64 -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:23.1.5.0-Final-java21-arm64
          ls -lRt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: target

  build-docker:
    needs: native-compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: target

      - name: Get version from pom.xml
        id: get_version
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$version" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          ls -lRt
          ls -lRt /
          docker build -f src/main/docker/Dockerfile.native-micro -t ${{ env.IMAGE_NAME }}:${{ env.version }} .
        env:
          DOCKER_BUILDKIT: 1

      - name: Push Docker image
        run: |
          echo "${{ secrets.TOKEN_DOCKER_HUB }}" | docker login -u "${{ secrets.LOGIN_DOCKER_HUB }}" --password-stdin
          docker push ${{ env.IMAGE_NAME }}:${{ env.version }}
