name: Chuck Norris action

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: amazoncorretto:21

    steps:
      - name: test
        run: ./mvnw quarkus:test
