name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: filhype-organization/universal-devops-action/.github/workflows/github-actions.yml@main
    with:
      build_type: 'native'
      build_platform: 'x86'
      container_build: true
      docker_image_name: 'leeson77/chuck-norris-backend'
      enable_java_build: false
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.LOGIN_DOCKER_HUB }}
      DOCKER_TOKEN: ${{ secrets.TOKEN_DOCKER_HUB }}